name: release
on:
  release:
    types: [published]
jobs:
  release:
    name: New resource pack version available!
    runs-on: minecraft-1.20.1
    steps:
    - name: discord
      uses: sebastianpopp/discord-action@releases/v2
      with:
        webhook: https://discord.com/api/webhooks/1219528976511275129/aad1UfdOnTdDqRFojewy2Rce81hfRJJA-WImagbQtG5uLBM-l5aOQtFBmx3-61oaaJ0t
        message: "The resource pack has been updated'.' Please download the newest version here > https://github.com/itisphxjupiter/curcuitcraft-resources/releases"